### ISSUE TITLE
reaction to ulster bank button press

### ISSUE THREAD

**Issue by jerry-appliedAIstudio** [dxc-technology/AI-Remote-Worker-Assistant#13]
Use the Toast (/assets/js/toast.js, Top Left Success) to respond to the Ulster Bank button push with an alert telling the user that we are updating the estimates using account transaction data.

The Toast playground is a good start
file:///C:/Users/jerry/OneDrive/Applied%20AI%20CoE/HTML%20Templates/template_102401_iERBBmp77p773Kddnxvv/Mylo%20HTML5%20Dashboard/Mylo%20HTML5%20Dashboard/pages/popups/toast.html

**Comment by at3362** [comment]
Added toast but progress bar is not showing

**Comment by jerry-appliedAIstudio** [comment]
Title: Bank APIs
Message: Using Bank APIs to update AI
